# Generated by Django 5.1.2 on 2024-10-13 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Yo'nalish ni kiriting", max_length=50, verbose_name="Yo'nalishlar")),
                ('created', models.DateTimeField(help_text="Yo'nalish ochilgan vaxt ni kiriting", verbose_name="Yo'nalish ochilgan vaxt")),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name="Yo'nalish yangilngan vaxt")),
                ('description', models.TextField(help_text="Yo'nalish bo'yicha qisqacha ma'lumot kiriitng", verbose_name="Yo'nalish bo'yicha qisqacha ma'lumot")),
                ('status', models.BooleanField(default=True, help_text="Yo'nalish faol yoki faol emas", verbose_name='Status')),
                ('image', models.ImageField(blank=True, help_text="Yo'nalish Rasmini kiriting", null=True, upload_to='directions/', verbose_name="Yo'nalish Rasmi")),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs nomini kiriting', max_length=100, verbose_name='Kurs Nomi')),
                ('duration', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, help_text="Kurs Haqida qisqacha ma'lumot", null=True)),
                ('start_date', models.DateTimeField(help_text='Kurs boshlanish vaxti')),
                ('end_date', models.DateTimeField(help_text='Kurs tugash vaxti')),
                ('created', models.DateTimeField(help_text='Kurs ochilgan vaxt')),
                ('price', models.DecimalField(decimal_places=2, help_text='Kurs narxini kiriting', max_digits=10, verbose_name='Kurs Narxi')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.direction')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Guruh nomi', max_length=5, verbose_name='Guruh nomi')),
                ('created', models.DateTimeField(help_text='Guruh ochilgan sanasi', verbose_name='Guruh ochilgan sanasi')),
                ('max_student', models.IntegerField(help_text="O'quvchilar soni", max_length=20, verbose_name="O'quvchilar soni")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Mavzu nomi', max_length=100, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, help_text="Mavzu haqida batafsil ma'lumot", null=True, verbose_name='Izoh')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Mavzu sanasi', verbose_name='Mavzu sanasi')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Mazvu yangilangan sana', verbose_name='Mazvu yangilangan sana')),
                ('video', models.FileField(upload_to='theme/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'ASF', 'FLV', 'MKV', 'MOV'])])),
                ('homework', models.CharField(help_text='Uyga vazifa', max_length=100, verbose_name='Uyga vazifa')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, help_text="Tug'ilgan sana", null=True, verbose_name="Tug'ilgan sana")),
                ('register_date', models.DateTimeField(help_text="Ro'yxatdan o'tgan sana", verbose_name="Ro'yxatdan o'tgan sana")),
                ('phone_number', models.IntegerField(help_text='Tel raqam', max_length=13, verbose_name='Tel raqam')),
                ('address', models.CharField(help_text='Yashash joyi', max_length=100, verbose_name='Yashash joyi')),
                ('full_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text="Qaysi guruhda o'qiydi", null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.group')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(help_text='Tel raqam', max_length=13, verbose_name='Tel raqam')),
                ('address', models.CharField(help_text='Yashash joyi', max_length=100, verbose_name='Yashash joyi')),
                ('last_login', models.DateTimeField(auto_now_add=True, help_text='Saytga kirgan vaxti', verbose_name='Saytga kirgan vaxti')),
                ('register_date', models.DateTimeField(help_text="Ro'yxatdan o'tgan sana", verbose_name="Ro'yxatdan o'tgan sana")),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='LikeOrDislikeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField(default=False, help_text='True()yoqdi, False(yoqmadi)', verbose_name='Like or Dislike')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan sana')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lesson')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Izoh', verbose_name='izoh')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name="Izoh qo'shilgan vaxt")),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='izoh yangilangan vaxt')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lesson')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Izoh', verbose_name='izoh')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name="Izoh qo'shilgan vaxt")),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='izoh yangilangan vaxt')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.parents')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Baxosi', max_digits=1, verbose_name='Baxosi')),
                ('added', models.DateTimeField(auto_now_add=True, help_text='Baxo berilgan vaxt', verbose_name='Baxo berilgan vaxt')),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='Baxo yangilangan vaxt', verbose_name='Baxo yangilangan vaxt')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_teacher', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(help_text='Ustozni Tajribasini kiriting', max_length=10, verbose_name='Ustozni Tajribasi')),
                ('phone_number', models.CharField(help_text='Ustozni Tel raqamini kiriting', max_length=13, verbose_name='Ustozni tel raqami')),
                ('is_active', models.BooleanField(default=True, help_text='Ustoz Ishlayabtimi ?')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(help_text='Ustozni Tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.teacher'),
        ),
    ]
