# Generated by Django 5.1.2 on 2024-10-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_group_max_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_student',
            field=models.CharField(help_text="O'quvchilar soni", max_length=13, verbose_name="O'quvchilar soni"),
        ),
        migrations.AlterField(
            model_name='parents',
            name='phone_number',
            field=models.CharField(help_text='Tel raqam', max_length=13, verbose_name='Tel raqam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Tel raqam', max_length=13, verbose_name='Tel raqam'),
        ),
    ]
