# Generated by Django 5.1.2 on 2024-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_group_max_student_alter_parents_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='rating',
            field=models.CharField(help_text='Baxosi', max_length=3, verbose_name='Baxosi'),
        ),
    ]
